[package]
name = "trippy"
version = "0.0.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "Placeholder (publish in Q2 2022)"
repository = "https://github.com/fujiapple852/trippy"
edition = "2021"

[dependencies]
