[package]
name = "trippy"
version = "0.0.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A network diagnostic tool"
repository = "https://github.com/fujiapple852/trippy"
license = "Apache-2.0"
edition = "2021"

[dependencies]
pnet = "0.29.0"
thiserror = "1.0.30"
derive_more = "0.99.17"